import {chromium} from '@playwright/test';import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import{xe,We}from'../src/engine/advanced.js';
const server=http.createServer(async(req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/guess-the-radionuclide/,'');if(p.endsWith('/'))p+='index.html';let file=path.resolve('dist','.'+p);if(!file.startsWith(path.resolve('dist')+path.sep))throw Error();const data=await fs.readFile(file);res.setHeader('Content-Type',({'html':'text/html','js':'application/javascript','css':'text/css','svg':'image/svg+xml','json':'application/json','webmanifest':'application/manifest+json','png':'image/png','wasm':'application/wasm'})[file.split('.').pop()]||'application/octet-stream');res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(4173,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true}),errors=[],checks=[];const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>Object.defineProperty(navigator,'gpu',{value:undefined,configurable:true}));const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:4173/guess-the-radionuclide/',click=name=>page.getByRole('button',{name,exact:true}).click();
try{
 await fs.mkdir('docs/screenshots',{recursive:true});await page.goto(base);await page.screenshot({path:'docs/screenshots/desktop.png',fullPage:true});checks.push('Desktop home');await click('English');assert.equal(await page.locator('html').getAttribute('lang'),'en');await click('Français');assert.equal(await page.locator('html').getAttribute('lang'),'fr');await click('Italiano');checks.push('IT/EN/FR switching');
 await click('English');await click('Learn before playing');assert((await page.locator('main').innerText()).includes('Protons and neutrons'));assert(await page.locator('img[src*="/tutorial/en/"]').count()>0);await page.screenshot({path:'docs/screenshots/tutorial-en.png',fullPage:true});await click('Français');assert((await page.locator('main').innerText()).includes('Protons et neutrons'));assert(await page.locator('img[src*="/tutorial/fr/"]').count()>0);await page.goto(base);await click('Italiano');checks.push('English and French lesson content and diagrams');
 await click('Atlante');await page.getByPlaceholder('Cerca radionuclide o storia').fill('Cs-137');await page.locator('[data-card-id="Cs-137"] button').first().click();await page.getByRole('dialog').waitFor();assert((await page.getByRole('dialog').innerText()).includes('661.657'));await page.screenshot({path:'docs/screenshots/evidence.png',fullPage:true});await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);checks.push('Atlas, sources and keyboard close');
 await page.goto(base);await click('Gioca');await click('Tutte');await click('Inizia la partita');await page.locator('[data-card-id="H-3"] button').first().click();await page.getByRole('textbox').fill('Emette particelle alfa?');await click('Fai la domanda');await page.getByRole('dialog').waitFor();assert((await page.getByRole('dialog').innerText()).includes('Decade alfa'));await click('Sì, chiedi questo');await page.getByText('Risposta',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Tenta di indovinare',exact:true}).count(),0);await page.screenshot({path:'docs/screenshots/game.png',fullPage:true});checks.push('Confirm question; no same-turn guess');if(await page.getByRole('button',{name:'Continua senza esercizio',exact:true}).count())await click('Continua senza esercizio');await click('Ho finito · turno successivo');const cq=await page.locator('h2').filter({hasText:'Il computer domanda:'}).locator('..').locator('p.bg-blue-50').innerText();const ca=We(xe['H-3'],cq);assert.equal(ca.type,'ok');await click(ca.yes?'SÌ':'NO');await page.getByRole('textbox').waitFor();checks.push('Computer turn');
 if(await page.getByRole('button',{name:'LLM non installata',exact:true}).count()){assert(await page.getByRole('button',{name:'LLM non installata',exact:true}).isDisabled());checks.push('No missing-model download offered; offline interpreter available');}else{await page.getByRole('button',{name:/Scarica LLM/}).click();await page.getByText(/LLM non disponibile/).waitFor();checks.push('Fallback with deliberately unavailable WebGPU');}
 await page.goto(base);await click('Gioca');await click('Due giocatori · un dispositivo');await click('Tutte');await click('Inizia la partita');
 await page.locator('[data-card-id="H-3"] button').first().click();await click('Sono pronto');
 await page.locator('[data-card-id="F-18"] button').first().click();await click('Sono pronto');
 assert.equal(await page.getByRole('textbox').count(),0);
 assert(!(await page.locator('aside').innerText()).includes('Fluoro-18'));
 await page.locator('[data-card-id="C-14"]').getByRole('button',{name:'Escludi carta'}).click();
 await click('Fine turno');assert(await page.locator('main').evaluate(e=>e.inert));await click('Sono pronto');
 assert.equal(await page.locator('[data-card-id="C-14"]').getByRole('button',{name:'Ripristina carta'}).count(),0);
 await page.locator('[data-card-id="F-18"]').getByRole('button',{name:'Escludi carta'}).click();
 await click('Fine turno');await click('Sono pronto');
 assert.equal(await page.locator('[data-card-id="C-14"]').getByRole('button',{name:'Ripristina carta'}).count(),1);
 assert.equal(await page.locator('[data-card-id="F-18"]').getByRole('button',{name:'Ripristina carta'}).count(),0);
 await click('Tenta di indovinare');await page.locator('[data-card-id="C-14"] button').first().click();
 await click('Conferma il tentativo');await click('Sono pronto');
 assert((await page.locator('aside').innerText()).includes('Tentativo errato'));
 await click('Fine turno');await click('Sono pronto');
 await click('Tenta di indovinare');await page.locator('[data-card-id="F-18"] button').first().click();
 await click('Conferma il tentativo');assert((await page.locator('body').innerText()).includes('ha indovinato!'));
 checks.push('Local spoken/manual play, independent boards, privacy, confirmed wrong/correct guesses');
 await page.goto(base);await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await context.setOffline(true);await page.reload();await click('Atlante');assert.equal(await page.locator('[data-card-id]').count(),59);await context.setOffline(false);checks.push('Offline reload and 59 cards');
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.screenshot({path:'docs/screenshots/mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await click('Gioca');await page.addStyleTag({content:'html{font-size:200%}'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('Mobile and 200% text');
 await page.goto(base);await click('Gioca');await click('Due giocatori · online');await click('Inizia la partita');
 await page.getByText('Multiplayer online non ancora configurato. Consulta la guida Firebase del progetto.',{exact:true}).waitFor();
 await click('Torna al menu');await context.setOffline(true);await click('Gioca');await click('Due giocatori · online');await click('Inizia la partita');
 await page.getByText('Per giocare online serve una connessione. Le altre modalità funzionano offline.',{exact:true}).first().waitFor();await context.setOffline(false);
 checks.push('Missing Firebase config and offline online-entry explain limits without breaking other modes');
 assert.deepEqual(errors,[]);const report={date:new Date().toISOString(),checks,passed:checks.length,pageErrors:errors,llmInference:'Generative inference not part of the game test; missing-model state verified, WebGPU disabled deliberately'};await fs.writeFile('docs/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){await page.screenshot({path:'docs/screenshots/failure.png',fullPage:true});console.log((await page.locator('body').innerText()).slice(0,1600));throw e;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
